import json
import argparse
from datetime import datetime
from pathlib import Path
from src.rando_parsers.pkmn_randomizer_log_parser import PkmnRandomizerLogParser

# TODO:
# - verify html compat with gen 6/7/8/9 randos
# - verify txt compat with gen 5+ randos
# - write script to gather and generate the vanilla json for all games
# - rewrite generate_random_team logic to accept new data format from rando log parser


def create_args_parser():
    # old parser:
    parser = argparse.ArgumentParser("parse_randomizer_log")
    parser.add_argument(
        "logfile",
        help="""The logfile generated by the randomizer. 
        Accepts both ".log" files produced by most branches of the UPR 
        as well as ".log.htm" files produced by the Brentspector release.""",
        type=Path,
    )

    parser.add_argument(
        "-o",
        "--outfile",
        help="""Filename to write the parsed data to. 
        If not provided, writes to a local file called "parsed_randolog_{now}"
        """,
        type=Path,
    )

    parser.add_argument(
        "-d",
        "--debug",
        action="store_true",
        help="""For debug purposes. Do not output to file."""
    )

    return parser


if __name__ == "__main__":
    args_parser = create_args_parser()
    args = args_parser.parse_args()

    logfile: Path = args.logfile
    if logfile.suffix == ".log":
        parser = PkmnRandomizerLogParser.from_txt(logfile_path=logfile)
    elif logfile.suffix.startswith(".htm"):
        parser = PkmnRandomizerLogParser.from_htm(htm_logfile_path=logfile)
    else:
        raise TypeError("Log is neither a .log nor a .htm; aborting.")

    if args.outfile is None:
        currtime = datetime.today().strftime("%Y%m%d%H%M")
        outfile = Path(f"parsed_randolog_{currtime}")
    else:
        outfile = args.outfile

    if outfile.suffix != ".json":
        outfile = outfile.with_suffix(".json")

    if (args.debug):
        print(parser.pkmn_stats)
        print(parser.pkmn_by_location)
        print(parser.wild_pkmn)
        print("DEBUGGING FINISHED.")
    else:
        print(f"\t\t> Writing parsed data to {outfile}.")
        with open(outfile, "w+") as fp:
            pkmn_data = {
                "stats": parser.pkmn_stats,
                "locations": parser.pkmn_by_location,
                "wild_pkmn": list(parser.wild_pkmn),
            }
            json.dump(pkmn_data, fp)
