import argparse
import pathlib
import random
from parser_types import PkmnRandomizerLogParser


def test(htm_logfile: str = "", txt_logfile: str = ""):
    if len(htm_logfile) == 0:
        htm_logfile = "./testing/test_emerald.gba.log.html"
    if len(txt_logfile) == 0:
        txt_logfile = "./testing/test_zx_emerald.gba.log"

    print("Test.")
    htm_parser = PkmnRandomizerLogParser.from_htm(htm_logfile)
    txt_parser = PkmnRandomizerLogParser.from_txt(txt_logfile)

    test_pkmn = "METAGROSS"
    htm_testpkmn = htm_parser.get_stats_for_pkmn(test_pkmn)
    txt_testpkmn = txt_parser.get_stats_for_pkmn(test_pkmn)

    print(htm_testpkmn)
    print(txt_testpkmn)

    htm_testpkmn_locs = htm_parser.get_locations_for_pkmn(test_pkmn)
    txt_testpkmn_locs = txt_parser.get_locations_for_pkmn(test_pkmn)

    print(list(htm_testpkmn_locs))
    print(list(txt_testpkmn_locs))

def write_data_to_file(parser: PkmnRandomizerLogParser):
    
    raise NotImplementedError

def create_args_parser():
    # old parser: 
    parser = argparse.ArgumentParser("parse_randomizer_log")
    parser.add_argument(
        "logfile",
        help="The logfile generated by the randomizer",
        type=pathlib.Path)
    
    parser.add_argument(
        "-o",
        "--outfile",
        help="File to write the parsed Pokemon data to",
        type=argparse.FileType('w', encoding="utf-8")
    )

    parser.add_argument("-f", "--find",
                        help="Pokemon to retrieve all possible locations for")

    parser.add_argument(
        "--noloc",
        help="When extracting Pokemon, do not include their locations.",
        action=argparse.BooleanOptionalAction)
    
    return parser

if __name__ == "__main__":
    args_parser = create_args_parser()
    args = args_parser.parse_args()
    test()

    # if args.find:
    #     print(f"finding locations of {args.find}")
    #     res = find_pokemon_locations_in_file(args.logfile, args.find)
    # elif args.withloc:
    #     print(f"grabbing pokemon and their locations")
    #     (pkmn, locs) = extract_from_file(args.logfile, True)
    #     res = [f"{p}: {', '.join(locs[p])}" for p in pkmn]
    # else:
    #     print(f"grabbing pokemon")
    #     pkmn = extract_from_file(args.logfile, False)
    #     res = list(pkmn)

    # if args.outfile:
    #     write_wild_pkmn_to_file(args.outfile, res)
    # else:
    #     print(res)