import json
import argparse
from datetime import datetime
from pathlib import Path
from src.rando_parsers.parser_types import PkmnRandomizerLogParser


def write_data_to_file(parser: PkmnRandomizerLogParser):
    raise NotImplementedError


def create_args_parser():
    # old parser:
    parser = argparse.ArgumentParser("parse_randomizer_log")
    parser.add_argument(
        "logfile", help="The logfile generated by the randomizer", type=Path
    )

    parser.add_argument(
        "-o", "--outfile", help="Filename to write the parsed data to.", type=Path
    )

    return parser


if __name__ == "__main__":
    args_parser = create_args_parser()
    args = args_parser.parse_args()

    logfile: Path = args.logfile
    if logfile.suffix == ".log":
        parser = PkmnRandomizerLogParser.from_txt(logfile_path=logfile)
    elif logfile.suffix.startswith(".htm"):
        parser = PkmnRandomizerLogParser.from_htm(htm_logfile_path=logfile)
    else:
        raise TypeError("Log is neither a .log nor a .htm; aborting.")

    if args.outfile is None:
        currtime = datetime.today().strftime("%Y%m%d%H%M")
        outfile = Path(f"parsed_randolog_{currtime}")
    else:
        outfile = args.outfile

    if outfile.suffix != ".json":
        outfile = outfile.with_suffix(".json")

    print(f"\t\t> Writing parsed data to {outfile}.")
    with open(outfile, "w+") as fp:
        pkmn_data = {
            "stats": parser.pkmn_stats,
            "locations": parser.pkmn_by_location,
            "wild_pkmn": list(parser.wild_pkmn),
        }
        json.dump(pkmn_data, fp)
